{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "influxdb.fullname" . }}"
  labels:
    app: "{{ template "influxdb.fullname" . }}"
    chart: "{{ template "influxdb.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "influxdb.fullname" . }}
          servicePort: 8086
{{- end -}}
